# Colors
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

# Index from 1
set -g base-index 1
setw -g pane-base-index 1

# Mouse
set -g mouse on

# Split panes
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# Reload config
bind r source-file ~/.tmux.conf \; display "Reloaded"

# History
set -g history-limit 10000

# No delay for escape
set -sg escape-time 0

# Copy mode (vi)
setw -g mode-keys vi
